services:
  - type: web
    name: finance-manager-api
    runtime: java
    plan: free

    buildCommand: mvn clean install
    startCommand: java -jar target/*.jar

    envVars:
      - key: JAVA_VERSION
        value: 17

      - key: SPRING_PROFILES_ACTIVE
        value: production

      - key: SERVER_PORT
        value: 8080

    healthCheckPath: /actuator/health

    autoDeploy: true